### PR TITLE
Added more comments; unified indentations

### PR DESCRIPTION
**Pull request by synthomat**
Thanks for the code! It helped me a lot on understanding CQRS :-)

Unfortunately I didn't manage to get the code running but I hope my comments are appropriate and correct.
I also uniformed the indentation in some files.

Cheers

### CODE REVIEW

**Comment by gregoryyoung** [comment]
what was the issue with running?

On Wed, Jan 14, 2015 at 1:15 AM, Anton Zering <notifications@github.com>
wrote:

> Thanks for the code! It helped me a lot on understanding CQRS :-)
>
> Unfortunately I didn't manage to get the code running but I hope my
> comments are appropriate and correct.
> I also uniformed the indentation in some files.
>
> Cheers
> ------------------------------
> You can merge this Pull Request by running
>
>   git pull https://github.com/synthomat/m-r master
>
> Or view, comment on, or merge it at:
>
>   https://github.com/gregoryyoung/m-r/pull/6
> Commit Summary
>
>    - Added more comments; unified indentations
>
> File Changes
>
>    - *M* SimpleCQRS/CommandHandlers.cs
>    <https://github.com/gregoryyoung/m-r/pull/6/files#diff-0> (7)
>    - *M* SimpleCQRS/Commands.cs
>    <https://github.com/gregoryyoung/m-r/pull/6/files#diff-1> (100)
>    - *M* SimpleCQRS/Domain.cs
>    <https://github.com/gregoryyoung/m-r/pull/6/files#diff-2> (4)
>    - *M* SimpleCQRS/EventStore.cs
>    <https://github.com/gregoryyoung/m-r/pull/6/files#diff-3> (23)
>    - *M* SimpleCQRS/Events.cs
>    <https://github.com/gregoryyoung/m-r/pull/6/files#diff-4> (64)
>    - *M* SimpleCQRS/FakeBus.cs
>    <https://github.com/gregoryyoung/m-r/pull/6/files#diff-5> (9)
>    - *M* SimpleCQRS/InfrastructureCrap.DontBotherReadingItsNotImportant.cs
>    <https://github.com/gregoryyoung/m-r/pull/6/files#diff-6> (2)
>    - *M* SimpleCQRS/Message.cs
>    <https://github.com/gregoryyoung/m-r/pull/6/files#diff-7> (9)
>    - *M* SimpleCQRS/ReadModel.cs
>    <https://github.com/gregoryyoung/m-r/pull/6/files#diff-8> (8)
>
> Patch Links:
>
>    - https://github.com/gregoryyoung/m-r/pull/6.patch
>    - https://github.com/gregoryyoung/m-r/pull/6.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gregoryyoung/m-r/pull/6>.
>



-- 
Studying for the Turing test

**Comment by synthomat** [comment]
The solution could not be opened because the debug package could not be loaded correctly. I think my  VS installation is somehow broken. I'm investigating...

**Comment by synthomat** [comment]
@gregoryyoung wohoo, got it running. VS was really broken.
The app works like charm :)

**Comment by gregoryyoung** [comment]
ok cool

On Wed, Jan 14, 2015 at 2:56 AM, Anton Zering <notifications@github.com>
wrote:

> @gregoryyoung <https://github.com/gregoryyoung> wohoo, got it running. VS
> was really broken.
> The app works like charm :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gregoryyoung/m-r/pull/6#issuecomment-69851672>.
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
thanks!

**Pull request merged**
